on: push
name: php-7.3-validate
jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: paajake/laravel-test-runner:7.3

    steps:
    - uses: actions/checkout@v1
    - run: goss --gossfile 7.3/goss.yaml validate
